// import { BodyParser } from 'body-parser';
var bodyParser = require('body-parser');
// import { express } from 'express';
var express = require('express');
var dbConnect = require('./config/dbConnect');
var _a = require('./middlewares/errorHandler'), notFound = _a.notFound, errorHandler = _a.errorHandler;
var app = express();
var dotenv = require('dotenv').config();
var PORT = process.env.PORT || 4000;
var authRouter = require("./routes/authRoute");
var productRouter = require("./routes/productRoute");
var categoryRouter = require("./routes/productCategoryRoute");
var brandRouter = require("./routes/brandRoute");
var couponRouter = require("./routes/couponRoute");
var cookieParser = require("cookie-parser");
var morgan = require("morgan");
dbConnect();
app.use(morgan("dev"));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cookieParser());
app.use('/api/user', authRouter);
app.use('/api/product', productRouter);
app.use('/api/category', categoryRouter);
app.use('/api/brand', brandRouter);
app.use('/api/coupon', couponRouter);
app.use(notFound);
app.use(errorHandler);
app.listen(PORT, function () {
    console.log("server is running at PORT ".concat(PORT));
});
